### ISSUE TITLE
Questions on testing with heterogenous LiDAR modalities for semantic segmentation

### ISSUE THREAD

**Issue by hwan0806** [Weixin-Ma/tripletloc#4]
It's a great paper! I look forward to its release soon.

By the way, I have a question.
As far as I know, the HeLiPR dataset utilizes various types of LiDARs (Ouster, Aeva, Avia, Velodyne).
Have you tested your method across different LiDAR modalities as well?

It seems to me that semantic segmentation methods might face challenges in generalizing to non-rotating LiDAR types 
such as Aeva or Avia LiDARs, which could be an area of concern.
I’d be grateful to hear your thoughts on this. Thank you.

**Comment by Weixin-Ma** [comment]
Hi there, 

Thank you for your kind words and the good question. 

So far,  we have only test our method using scans from Ouster or Velodyne. The semantic segmentation result is actually not very good , we would describe them as "acceptable" or "reasonable" (examples can be found in [issue #2](https://github.com/Weixin-Ma/TripletLoc/issues/2)). We believe that fine-tuning the [SPVNAS](https://github.com/mit-han-lab/spvnas) model on HeLiPR could improve the results.

As for scans from Avia LiDARs, we think that accumulated scans (i.e., submaps) might have the potential to achieve better semantic segmentation when using models trained on rotating LiDARs.

Best,
weixin

**Comment by hwan0806** [comment]
Thank you for your kind and detailed response, as well as for providing specific solutions to address the issue. 
I sincerely hope that future research in computer vision will help resolve this problem. I will close this issue now.
